# Generated by Django 4.2.6 on 2023-10-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='prouduct',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
